name: Live Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  live-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        
    - name: Install dependencies
      run: |
        pdm config python.use_venv true
        pdm venv create
        pdm install
        pdm add -d pytest pytest-cov pytest-mock
        
    - name: Run live tests
      run: |
        . .venv/bin/activate
        pdm run pytest live_tests/ -v