name: Live Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  live-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        
    - name: Install dependencies
      run: |
        pdm lock
        pdm install -G dev
        
    - name: Run live tests
      run: |
        pdm run pytest live_tests/ -v